core:
  - all:
      - changed-files:
          - any-glob-to-any-file: "lua/cobalt2/**"
          - all-globs-to-all-files:
              - "!lua/cobalt2/groups/**"
              - "!lua/cobalt2/colors/**"

groups:
  - changed-files:
      - any-glob-to-any-file: "lua/cobalt2/groups/**"

base:
  - changed-files:
      - any-glob-to-any-file:
          - "lua/cobalt2/groups/base.lua"
          - "lua/cobalt2/groups/kinds.lua"
          - "lua/cobalt2/groups/treesitter.lua"
          - "lua/cobalt2/groups/semantic_tokens.lua"

colors:
  - changed-files:
      - any-glob-to-any-file: "lua/cobalt2/colors/**"
